- simulation1:
    consensus_name: Fruitchain
    miners:
      honest:
        mining_power: 90
      selfish:
        - mining_power: 10
    gamma: 0.0
    simulation_mining_rounds: 200_000
    fruit_mine_prob: 0.8
    superblock_prob: 0.2
