- simulation1:
    consensus_name: Fruitchain
    miners:
      honest:
        mining_power: 60
      selfish:
        - mining_power: 40
    gamma: 0.5
    simulation_mining_rounds: 200_000
    fruit_mine_prob: 0.8
    superblock_prob: 0.2
